[package]
name = "cms-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cms-core = { path = "../../crates/cms-core" }
cms-db = { path = "../../crates/cms-db" }
cms-pubsub = { path = "../../crates/cms-pubsub" }
cms-render = { path = "../../crates/cms-render" }
cms-workflows = { path = "../../crates/cms-workflows" }
dotenvy.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
